name: Build and Publish Docker Image

on:
  repository_dispatch:
    types: [new-release]

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Binary from Repo A
        run: |
          curl -L -o chained-ci-example \
          "https://github.com/knelasevero/chained-ci-example/releases/download/${{ github.event.client_payload.tag_name }}/chained-ci-example"
          chmod +x chained-ci-example
          ls
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/knelasevero/chained-ci-cross-repo-example:${{ github.event.client_payload.tag_name }}